### ISSUE TITLE
Invalid Syntax on Valid blog link

### ISSUE THREAD

**Issue by rileyborgard** [meooow25/cfspy#24]
I posted the blog post like this:

https://codeforces.com/blog/entry/85638

and got the following error:

Error fetching blog from https://codeforces.com/blog/entry/85638: strconv.Atoi: parsing "": invalid syntax

**Comment by meooow25** [comment]
Can't reproduce it, seems to be working as expected right now 🤔
The only `Atoi` for a blog is to parse the rating, so maybe CF wasn't returning a proper blog page.

**Comment by meooow25** [comment]
Was able to reproduce this, happens when locale is set to Russian.
