### ISSUE TITLE
Bot not removing default embeds in community servers

### ISSUE THREAD

**Issue by iampjeetsingh** [meooow25/cfspy#41]
Actually to be able to remove embeds moderators need to enable 2fa on their account If the server is a community server.
Similarly for bots the owner of the bot must enable 2fa on his account for the bot to be able to remove embeds.

**Comment by meooow25** [comment]
Hi, thanks I wasn't aware of that. I've enabled 2fa now so let me know if it works.

**Comment by iampjeetsingh** [comment]
Yeah, Its working fine now.
