### ISSUE TITLE
Error fetching blog - invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by osalbahr** [meooow25/cfspy#44]
Error message:
Error fetching blog from https://codeforces.com/blog/entry/4088: invalid character '<' looking for beginning of value
If this is a reproducible bug, please [report it](https://github.com/meooow25/cfspy/issues).

Reproducible?
Yes. I tried multiple channels in the same server.

**Comment by meooow25** [comment]
Thanks for reporting. Yes, I think it's likely that the Codeforces API responded with HTML instead of JSON, making the parser return that particular error. I agree that it would be a good idea to add some context to the error messages, will implement it 👍
